import {
  Box,
  Layout,
  Navigation,
  Image,
  Bell,
  BarChart,
  Zap,
  MousePointer2,
  Type,
  FileText,
  CheckSquare,
  Circle,
  ToggleLeft,
  Ruler,
  ChevronDown,
  TrendingUp,
  Square,
  Layers,
  LayoutGrid,
  Grid3X3,
  Layers2,
  Group,
  Columns,
  AlignJustify,
  Menu,
  ChevronRight,
  MoreHorizontal,
  Navigation2,
  ListTree,
  User,
  Star,
  Video,
  Volume2,
  Grid,
  ArrowLeftRight,
  AlertCircle,
  MessageCircle,
  Award,
  RotateCw,
  Table,
  List,
  Gauge,
  Clock,
  Calendar,
  Wand2,
  Edit,
  Code,
  Map,
  Search,
} from "lucide-react";
import { ElementCategory } from "./types";

export const elementLibrary: ElementCategory[] = [
  {
    category: "Basic Elements",
    icon: Box,
    elements: [
      { id: "button", label: "Button", icon: MousePointer2, color: "bg-blue-500", description: "Interactive button component" },
      { id: "input", label: "Input Field", icon: Type, color: "bg-green-500", description: "Text input field" },
      { id: "textarea", label: "Textarea", icon: FileText, color: "bg-purple-500", description: "Multi-line text input" },
      { id: "label", label: "Label", icon: Type, color: "bg-orange-500", description: "Text label for form elements" },
      { id: "checkbox", label: "Checkbox", icon: CheckSquare, color: "bg-teal-500", description: "Boolean input control" },
      { id: "radio", label: "Radio Button", icon: Circle, color: "bg-pink-500", description: "Single selection control" },
      { id: "switch", label: "Toggle Switch", icon: ToggleLeft, color: "bg-indigo-500", description: "On/off toggle control" },
      { id: "slider", label: "Slider", icon: Ruler, color: "bg-cyan-500", description: "Range input control" },
      { id: "select", label: "Select Dropdown", icon: ChevronDown, color: "bg-violet-500", description: "Selection dropdown" },
      { id: "progress", label: "Progress Bar", icon: TrendingUp, color: "bg-emerald-500", description: "Progress indicator" },
    ]
  },
  {
    category: "Layout Components",
    icon: Layout,
    elements: [
      { id: "container", label: "Container", icon: Square, color: "bg-gray-500", description: "Basic container element" },
      { id: "card", label: "Card", icon: Box, color: "bg-indigo-500", description: "Content card container" },
      { id: "panel", label: "Panel", icon: Layers, color: "bg-slate-500", description: "Sectioned content panel" },
      { id: "flex", label: "Flex Container", icon: LayoutGrid, color: "bg-teal-500", description: "Flexible layout container" },
      { id: "grid", label: "Grid", icon: Grid3X3, color: "bg-cyan-500", description: "CSS Grid layout" },
      { id: "stack", label: "Stack", icon: Layers2, color: "bg-blue-600", description: "Vertical stack layout" },
      { id: "cluster", label: "Cluster", icon: Group, color: "bg-green-600", description: "Horizontal cluster layout" },
      { id: "sidebar", label: "Sidebar", icon: Columns, color: "bg-purple-600", description: "Navigation sidebar" },
      { id: "header", label: "Header", icon: AlignJustify, color: "bg-red-500", description: "Page header section" },
      { id: "footer", label: "Footer", icon: AlignJustify, color: "bg-red-600", description: "Page footer section" },
    ]
  },
  {
    category: "Navigation",
    icon: Navigation,
    elements: [
      { id: "navbar", label: "Navigation Bar", icon: Menu, color: "bg-blue-600", description: "Main navigation bar" },
      { id: "breadcrumb", label: "Breadcrumb", icon: ChevronRight, color: "bg-orange-600", description: "Navigation breadcrumb" },
      { id: "tabs", label: "Tabs", icon: Layers, color: "bg-purple-600", description: "Tabbed navigation" },
      { id: "pagination", label: "Pagination", icon: MoreHorizontal, color: "bg-green-600", description: "Page navigation" },
      { id: "menu", label: "Dropdown Menu", icon: ChevronDown, color: "bg-red-600", description: "Contextual menu" },
      { id: "stepper", label: "Stepper", icon: Navigation2, color: "bg-indigo-600", description: "Step-by-step navigation" },
      { id: "tree", label: "Tree Navigation", icon: ListTree, color: "bg-cyan-600", description: "Hierarchical navigation" },
    ]
  },
  {
    category: "Media & Content",
    icon: Image,
    elements: [
      { id: "image", label: "Image", icon: Image, color: "bg-pink-500", description: "Image display component" },
      { id: "avatar", label: "Avatar", icon: User, color: "bg-rose-500", description: "User profile image" },
      { id: "icon", label: "Icon", icon: Star, color: "bg-yellow-500", description: "Icon display" },
      { id: "video", label: "Video Player", icon: Video, color: "bg-red-500", description: "Video playback component" },
      { id: "audio", label: "Audio Player", icon: Volume2, color: "bg-green-500", description: "Audio playback component" },
      { id: "gallery", label: "Gallery", icon: Grid, color: "bg-purple-500", description: "Image gallery" },
      { id: "carousel", label: "Carousel", icon: ArrowLeftRight, color: "bg-blue-500", description: "Content carousel" },
      { id: "masonry", label: "Masonry Grid", icon: Grid, color: "bg-indigo-500", description: "Masonry layout grid" },
    ]
  },
  {
    category: "Feedback & Status",
    icon: Bell,
    elements: [
      { id: "alert", label: "Alert", icon: AlertCircle, color: "bg-yellow-500", description: "Alert notification" },
      { id: "toast", label: "Toast", icon: Bell, color: "bg-green-500", description: "Toast notification" },
      { id: "modal", label: "Modal", icon: Layers, color: "bg-red-500", description: "Modal dialog" },
      { id: "tooltip", label: "Tooltip", icon: MousePointer2, color: "bg-emerald-500", description: "Hover tooltip" },
      { id: "popover", label: "Popover", icon: MessageCircle, color: "bg-blue-500", description: "Contextual popover" },
      { id: "badge", label: "Badge", icon: Award, color: "bg-purple-500", description: "Status badge" },
      { id: "spinner", label: "Loading Spinner", icon: RotateCw, color: "bg-gray-500", description: "Loading indicator" },
      { id: "skeleton", label: "Skeleton", icon: Box, color: "bg-slate-400", description: "Content placeholder" },
    ]
  },
  {
    category: "Data Display",
    icon: BarChart,
    elements: [
      { id: "table", label: "Data Table", icon: Table, color: "bg-blue-600", description: "Data display table" },
      { id: "list", label: "List", icon: List, color: "bg-green-600", description: "Item list component" },
      { id: "chart", label: "Chart", icon: BarChart, color: "bg-purple-600", description: "Data visualization chart" },
      { id: "gauge", label: "Gauge", icon: Gauge, color: "bg-orange-600", description: "Circular gauge meter" },
      { id: "timeline", label: "Timeline", icon: Clock, color: "bg-red-600", description: "Event timeline" },
      { id: "calendar", label: "Calendar", icon: Calendar, color: "bg-indigo-600", description: "Date picker calendar" },
      { id: "kanban", label: "Kanban Board", icon: Columns, color: "bg-cyan-600", description: "Task management board" },
    ]
  },
  {
    category: "Advanced",
    icon: Zap,
    elements: [
      { id: "form", label: "Form", icon: FileText, color: "bg-blue-700", description: "Complete form component" },
      { id: "wizard", label: "Wizard", icon: Wand2, color: "bg-purple-700", description: "Multi-step wizard" },
      { id: "editor", label: "Rich Text Editor", icon: Edit, color: "bg-green-700", description: "WYSIWYG text editor" },
      { id: "code", label: "Code Block", icon: Code, color: "bg-gray-700", description: "Syntax highlighted code" },
      { id: "map", label: "Interactive Map", icon: Map, color: "bg-red-700", description: "Map component" },
      { id: "chat", label: "Chat Interface", icon: MessageCircle, color: "bg-indigo-700", description: "Chat conversation UI" },
      { id: "search", label: "Search Bar", icon: Search, color: "bg-yellow-600", description: "Search input with suggestions" },
    ]
  }
];