export const defaultProps: Record<string, any> = {
  button: {
    text: "Click me",
    variant: "primary",
    size: "medium",
    disabled: false,
    loading: false,
    fullWidth: false,
    leftIcon: null,
    rightIcon: null,
  },
  input: {
    placeholder: "Enter text...",
    type: "text",
    value: "",
    disabled: false,
    required: false,
    error: false,
    helperText: "",
    leftIcon: null,
    rightIcon: null,
  },
  textarea: {
    placeholder: "Enter text...",
    value: "",
    rows: 3,
    disabled: false,
    required: false,
    error: false,
    helperText: "",
    resize: "vertical",
  },
  label: {
    text: "Label",
    required: false,
    size: "medium",
    color: "default",
  },
  checkbox: {
    label: "Checkbox",
    checked: false,
    disabled: false,
    indeterminate: false,
    size: "medium",
  },
  radio: {
    label: "Radio Option",
    value: "option1",
    checked: false,
    disabled: false,
    size: "medium",
  },
  switch: {
    label: "Toggle",
    checked: false,
    disabled: false,
    size: "medium",
  },
  slider: {
    min: 0,
    max: 100,
    value: 50,
    step: 1,
    disabled: false,
    showValue: true,
    orientation: "horizontal",
  },
  select: {
    placeholder: "Select option...",
    options: ["Option 1", "Option 2", "Option 3"],
    value: "",
    disabled: false,
    multiple: false,
    searchable: false,
  },
  progress: {
    value: 65,
    max: 100,
    color: "primary",
    size: "medium",
    showValue: true,
    animated: false,
  },
  container: {
    padding: { x: 16, y: 16 },
    margin: { x: 0, y: 0 },
    backgroundColor: "transparent",
    border: false,
    maxWidth: "none",
  },
  card: {
    padding: { x: 24, y: 24 },
    shadow: "medium",
    backgroundColor: "white",
    border: true,
    hover: false,
  },
  panel: {
    title: "Panel Title",
    collapsible: false,
    collapsed: false,
    padding: { x: 20, y: 20 },
    headerPadding: { x: 20, y: 12 },
  },
  flex: {
    direction: "row",
    justify: "flex-start",
    align: "stretch",
    wrap: "nowrap",
    gap: 8,
  },
  grid: {
    columns: 3,
    rows: "auto",
    gap: 16,
    justifyItems: "stretch",
    alignItems: "stretch",
  },
  stack: {
    spacing: 16,
    align: "stretch",
    distribute: "start",
  },
  image: {
    src: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=400&h=300&fit=crop",
    alt: "Placeholder image",
    objectFit: "cover",
    aspectRatio: "4/3",
    rounded: true,
  },
  avatar: {
    src: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=100&h=100&fit=crop&crop=face",
    alt: "User avatar",
    size: "medium",
    shape: "circle",
    fallback: "JD",
  },
  icon: {
    name: "star",
    size: 24,
    color: "currentColor",
    strokeWidth: 2,
  },
  alert: {
    title: "Alert Title",
    message: "This is an alert message",
    type: "info",
    dismissible: true,
    icon: true,
  },
  toast: {
    title: "Toast Title",
    message: "This is a toast message",
    type: "success",
    duration: 5000,
    position: "top-right",
  },
  modal: {
    title: "Modal Title",
    size: "medium",
    closeOnOverlay: true,
    showCloseButton: true,
    footerActions: true,
  },
  tooltip: {
    content: "Tooltip content",
    placement: "top",
    trigger: "hover",
    delay: 500,
  },
  badge: {
    text: "Badge",
    variant: "default",
    size: "medium",
  },
  table: {
    headers: ["Column 1", "Column 2", "Column 3"],
    rows: [
      ["Data 1", "Data 2", "Data 3"],
      ["Data 4", "Data 5", "Data 6"],
    ],
    striped: true,
    hover: true,
  },
  list: {
    items: ["Item 1", "Item 2", "Item 3"],
    ordered: false,
    spacing: "medium",
  },
};

export const defaultStyle: Record<string, any> = {
  borderRadius: 8,
  opacity: 1,
  zIndex: 1,
  backgroundColor: "transparent",
  borderWidth: 0,
  borderColor: "#000000",
  borderStyle: "solid",
};